### ISSUE TITLE
Clan Colors

### ISSUE THREAD

**Issue by FireController1847** [RoinujNosde/SimpleClans#13]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I think it'd be really nice to be able to have a "clan color" that you can use to describe your clan. If this gets implemented, I'd love to be able to then include the clan color inside of my username in the chat formatting. See additional context for an image example of what I'm looking for :)

**Describe alternatives you've considered**
There really isn't any alternative. It's just not supported currently.

**Additional context**
![image](https://user-images.githubusercontent.com/16494272/88029432-3e596400-caf7-11ea-8c57-53dd9a2ab942.png)

Tag Configuration:
```yml
tag:
  default-color: f
  max-length: 1
  min-length: 1
  separator:
    color: f
    leader-color: f
    char: ''
  bracket:
    color: f
    leader-color: f
    left: '['
    right: '] '
```
