### ISSUE TITLE
Customizar formatação do spy chat

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/SimpleClans#165]
**Is your feature request related to a problem? Please describe.**

Eu acho muito difícil ler o chat spy de clãs e aliados atualmente por causa da cor e formatação.
Não existe uma distinção do chat spy de clãs e aliados, ambos são exatamente iguais.

**Describe the solution you'd like**

Gostaria de poder customizar cada chat spy separadamente onde seria possível adicionar um prefixo para cada chat spy, poder usar os placeholders iguais ao chat normal.

**Describe alternatives you've considered**

Alternativa que eu considerei consiste em add uma opção na config como por exemplo:

```yml
spy-allychat:
  format: '&8[spy] &3[a] &f[%clan%&f] %rank%%nick-color%%player%&8» &3%message%'
  rank: '&f[%rank%&f] '
  leader-color: '4'
  trusted-color: a
  member-color: f
spy-clanchat:
  format: "&8[spy] &b[%clan%&b] &4<%nick-color%%player%&4> %rank%: &b%message%"
  rank: "&f[%rank%&f]"
  leader-color: '4'
  trusted-color: 'f'
  member-color: '7'
  ```
