### ISSUE TITLE
Config land-creation only-leaders still has no effect

### ISSUE THREAD

**Issue by Sogekeeper** [RoinujNosde/SimpleClans#258]
Plugin version: Build #193 (Sat Sep 25 19:27:29 UTC 2021) **(Jenkins)**
Server runs the latest version of Magma for 1.12.2

Server is using enable-auto-groups and auto-group-groupname.
Vault, LuckPerms and GriefPrevention are installed.

The following config still has no effect. A player with no clan or any other status other than leader (group sc_untrusted, sc_trusted and default from luckperms) can still use the golden shovel to create GriedPrevention lands.

`land-creation:
    only-leaders: true`

I have tried joining the server and using the shovel = The shovel works
Tried accepting the invitation to become a member of a clan = The shovel works

If I need to provide any other info please let me know

**Comment by Tomut0** [comment]
Hello there. 
It would be more **faster** to recognize the problem, if you will send your configuration file.

**Comment by Sogekeeper** [comment]
Hi there,
Here you go, my config.yml for SimpleClans

EDIT: Oops, seems like Github doesn't fold code sections, here's a txt file
[SimpleClans_Config.txt](https://github.com/RoinujNosde/SimpleClans/files/7245291/SimpleClans_Config.txt)

```
safe-civilians: false
tag:
  default-color: '8'
  max-length: 5
  bracket:
    color: '8'
    leader-color: '4'
    left: ''
    right: ''
  min-length: 2
  separator:
    color: '8'
    leader-color: '4'
    char: ' .'
settings:
  enable-gui: true
  disable-messages: false
  tameable-mobs-sharing: false
  teleport-blocks: false
  teleport-home-on-spawn: false
  drop-items-on-clan-home: false
  keep-items-on-clan-home: false
  item-list: []
  show-debug-info: false
  enable-auto-groups: true
  chat-compatibility-mode: true
  rival-limit-percent: 50
  use-colorcode-from-prefix-for-name: true
  display-chat-tags: true
  global-friendly-fire: true
  unrivable-clans:
  - admin
  - staff
  - mod
  show-unverified-on-list: false
  blacklisted-worlds: []
  banned-players: []
  disallowed-tags:
  - vip
  - clan
  language: en
  user-language-selector: true
  disallowed-tag-colors:
  - '4'
  server-name: '&4RecintoDoLordValdemiro'
  new-clan-verification-required: true
  allow-regroup-command: true
  allow-reset-kdr: false
  rejoin-cooldown: 25200
  rejoin-cooldown-enabled: true
  accept-other-alphabets-letters-on-tag: false
  ranking-type: DENSE
  list-default-order-by: kdr
  lore-length: 36
war-and-protection:
  war-enabled: true
  land-sharing: true
  protection-providers:
  - WorldGuardProvider
  - WorldGuard6Provider
  - PlotSquared5Provider
  - PlotSquared3Provider
  - GriefPreventionProvider
  listeners:
    priority: HIGHEST
    ignored-list:
      PLACE:
      - PLAYER_HEAD
      BREAK:
      - EMERALD_BLOCK
  set-base-only-in-land: false
  war-normal-expiration-time: 0
  war-disconnect-expiration-time: 5
  edit-all-lands: false
  land-creation:
    only-leaders: true
    only-one-per-clan: true
  war-actions:
    CONTAINER: true
    INTERACT: true
    BREAK: true
    PLACE: true
    DAMAGE: true
    INTERACT_ENTITY: true
  war-start:
    request-enabled: true
    members-online-max-difference: 5
kdr-grinding-prevention:
  enable-max-kills: true
  max-kills-per-victim: 1
  enable-kill-delay: false
  delay-between-kills: 5
commands:
  more: scmore
  ally: scally
  clan: clan
  accept: scaccept
  deny: scdeny
  global: scglobal
  clan_chat: .
  force-priority: true
economy:
  creation-price: 100.0
  purchase-clan-create: false
  verification-price: 1000.0
  purchase-clan-verify: false
  invite-price: 20.0
  purchase-clan-invite: false
  home-teleport-price: 5.0
  purchase-home-teleport: false
  home-teleport-set-price: 5.0
  purchase-home-teleport-set: false
  home-regroup-price: 5.0
  purchase-home-regroup: false
  unique-tax-on-regroup: true
  issuer-pays-regroup: true
  money-per-kill: false
  money-per-kill-kdr-multipier: 10
  purchase-reset-kdr: true
  reset-kdr-price: 10000.0
  purchase-member-fee-set: false
  member-fee-set-price: 1000.0
  member-fee-enabled: false
  member-fee-last-minute-change-interval: 8
  max-member-fee: 200.0
  upkeep: 200.0
  upkeep-enabled: false
  multiply-upkeep-by-clan-size: false
  charge-upkeep-only-if-member-fee-enabled: true
  bank-log:
    enable: true
kill-weights:
  rival: 2.0
  civilian: 0.0
  neutral: 1.0
  ally: -1.0
  deny-same-ip-kills: false
clan:
  homebase-teleport-wait-secs: 10
  homebase-can-be-set-only-once: true
  min-size-to-set-rival: 3
  max-length: 25
  max-description-length: 120
  min-description-length: 10
  max-members: 25
  confirmation-for-promote: false
  trust-members-by-default: false
  confirmation-for-demote: false
  percentage-online-to-demote: 100.0
  ff-on-by-default: true
  min-length: 2
  max-alliances: -1
  min-size-to-set-ally: 3
  min-to-verify: 1
tasks:
  collect-upkeep:
    hour: 1
    minute: 30
  collect-upkeep-warning:
    hour: 12
    minute: 0
  collect-fee:
    hour: 1
    minute: 0
page:
  untrusted-color: '8'
  clan-name-color: b
  subtitle-color: '7'
  headings-color: '8'
  trusted-color: f
  leader-color: '4'
  separator: '-'
  size: 100
clanchat:
  enable: true
  tag-based-clan-chat: false
  announcement-color: e
  format: '&b[%clan%&b] &4<%nick-color%%player%&4> %rank%: &b%message%'
  spy-format: '&8[Spy] [&bC&8] <%clean-tag%&8> <%nick-color%*&8%player%>&8 %rank%&8:
    %message%'
  rank: '&f[%rank%&f]'
  leader-color: '4'
  trusted-color: f
  member-color: '7'
request:
  message-color: b
  ask-frequency-secs: 60
  max-asks-per-request: 1440
bb:
  color: e
  accent-color: '8'
  show-on-login: true
  size: 6
  login-size: 6
allychat:
  enable: true
  format: '&b[Ally Chat] &4<%clan%&4> <%nick-color%%player%&4> %rank%: &b%message%'
  spy-format: '&8[Spy] [&cA&8] <%clean-tag%&8> <%nick-color%*&8%player%>&8 %rank%&8:
    %message%'
  rank: '&f[%rank%&f]'
  leader-color: '4'
  trusted-color: f
  member-color: '7'
discordchat:
  enable: false
  discord-format: '%player% » %message%'
  format: '&b[&9D&b] &b[%clan%&b] &4<%nick-color%%player%&4> %rank%: &b%message%'
  spy-format: '&8[Spy] [&9D&8] <%clean-tag%&8> <%nick-color%*&8%player%>&8 %rank%&8:
    %message%'
  rank: '[%rank%]'
  leader-role: Leader
  leader-color: 231, 76, 60, 100
  leader-id: 0
  text:
    category-format: SC - TextChannels
    category-ids: []
    whitelist: []
    clans-limit: 100
purge:
  inactive-player-data-days: 30
  inactive-clan-days: 7
  unverified-clan-days: 2
mysql:
  username: ''
  host: localhost
  port: 3306
  enable: false
  password: ''
  database: ''
permissions:
  auto-group-groupname: true
  YourClanNameHere:
  - test.permission
performance:
  save-periodically: true
  save-interval: 10
  use-threads: true
  use-bungeecord: false
```
