### ISSUE TITLE
Option for always Clanchat without command

### ISSUE THREAD

**Issue by vaporvee** [RoinujNosde/SimpleClans#276]
**Is your feature request related to a problem? Please describe.**
I have the discord integration on and the clan system is a big part on my server.
But its annoying to type /. every time i want to chat.

 **Describe the solution you'd like**
It would be cool if you could turn on something in the config.yml that swaps this whole situation.
So that you type /. to chat globaly and when you are in a clan you type just normaly in chat wich automatically sends it to the clan chat. Then you would also have somehow a option to add a tag for messages wich are sent in global chat and a tag for clan messages.
For example '[Global Chat]cmod31 > hi' and '[Clan Chat][Clannameher]cmod31 > hi' or something

Also nice plugin thanks

**Comment by RoinujNosde** [comment]
There is the sub command "join" that does a similar thing.
You run `/. join` and everything you write in chat goes to the clan chat.
Also works for ally chat.

**Comment by vaporvee** [comment]
Is there an config option that activates it as default?

**Comment by RoinujNosde** [comment]
Nope.

**Comment by vaporvee** [comment]
so could this be added?

**Comment by Tomut0** [comment]
> so could this be added?

You could probably run this command by players' join. I guess, there are a lot of ways to do it. 👀

**Comment by vaporvee** [comment]
can i run this command after something detects that the player has been added to a clan? When yes then how?

**Comment by RoinujNosde** [comment]
Only clan members are able to use that command. Others will just get a warning message.

**Comment by vaporvee** [comment]
hm still want a config feature then but its your plugin all good
Edit: oh you meant members yeah thats good but how can i run a comand when the player joins a clan

**Comment by RoinujNosde** [comment]
> how can i run a comand when the player joins a clan

That could be done using SimpleClans' API.

**Comment by SrBedrock** [comment]
An option could be added where sending `/.` without any arguments could access the clan chat?

**Comment by Tomut0** [comment]
@cmod31, Just a continue of my mind.

You could use Denizen:
```yml
# Runs clan chat command after player join
myclan_script:
  type: world
  events:
    after player join:
      - execute as_player "/. join" silent
 ```
 If you will use Depenizen (it's an extension for Denizen) and PlaceholderAPI:
 ```yml
# Runs clan chat command after player join, also checks if player is joined in clan or not
myclan_script:
  type: world
  events:
    after player join:
      - if <placeholder[simpleclans_in_clan]>:
        - execute as_player "/. join" silent
 ```
