### ISSUE TITLE
[Feature Request] Default Clan role by default

### ISSUE THREAD

**Issue by triesharder** [RoinujNosde/SimpleClans#416]
**Is your feature request related to a problem? Please describe.**

Not having a default role when a clan is created can lead to the necessity of adjusting each `display-name;
-> the problem of doing so is for when some players start to customize their own clans, they will have to remind of doing it too, for me it's a loss in experience quality

This also slightly reduces customization possibilities

![image](https://github.com/RoinujNosde/SimpleClans/assets/89689590/555e7989-305e-42de-aef5-4549d867e6d1)

**Describe the solution you'd like**
```
starter-ranks:
  - <role>:
      default: true
      display-name: 'very-stylish'
      permissions: []
```

**Describe alternatives you've considered**
`defaultRole: '<role>'` 
or having a warning to be sent right after clan creation reminding the owner to use `clan rank setdefault`
