### ISSUE TITLE
Erro ao usar a opção cache-player-heads: true

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/SimpleClans#49]
**Describe the bug**
Erro ao desligar o servidor usando opção `cache-player-heads: true`.
`[13:09:35 ERROR]: Nag author: 'Phaed' of 'SimpleClans' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.`

**To Reproduce**
1. Nas configurações adicione cache-player-heads: true
```yml
performance:
  cache-player-heads: true
  save-periodically: false
  save-interval: 10
  use-threads: true
  use-bungeecord: false
```
2. Desligue o servidor.

**Expected behavior**
Nenhum erro ao desligar o servidor.

**Software (please complete the following information):**
 - Server: Paper 1.16.1
 - Plugin version 2.13.1
