### ISSUE TITLE
Banners do not save on /clan reload or server reboot.

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#95]
**Describe the bug**
Clans set banners for their clan, the data is not saved between reboots or plugin reload BUT It looks like its being saved in the database.
Looking in my database I can see 8 Crews with banners saved, but they are not showing in-game after reboot or reloading the plugin;
```
cs:
  ==: org.bukkit.inventory.ItemStack
  type: BANNER
  meta:
    ==: ItemMeta
    meta-type: BANNER
    ItemFlags:
    - HIDE_POTION_EFFECTS
    patterns:
    - ==: Pattern
      color: WHITE
      pattern: sku
```
Is what I can see in the database from one crew.

**To Reproduce**
1. Set a banner to a clan
2. /clan reload
3. All banners vanish.

**Software (please complete the following information):**
 - Server: Paper 1.12.2
 - Plugin version 2.14.3
